### ISSUE TITLE
Instant query with no data causes a panic

### ISSUE THREAD

**Issue by fpetkovski** [thanos-community/promql-engine#17]
Looks like running an instant query against an empty series set series can cause a panic
```
panic: runtime error: index out of range [4] with length 0

goroutine 348 [running]:
github.com/thanos-community/promql-engine/physicalplan/aggregate.(*aggregate).workerTask(0x100e48a40?, 0x14000091668?, {0x0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}})
	/Users/fpetkovski/Projects/promql-engine/physicalplan/aggregate/hashaggregate.go:155 +0x11c
github.com/thanos-community/promql-engine/worker.(*Worker).Start(0x14000eacc80)
	/Users/fpetkovski/Projects/promql-engine/worker/worker.go:65 +0xdc
created by github.com/thanos-community/promql-engine/worker.Group.Start
	/Users/fpetkovski/Projects/promql-engine/worker/worker.go:24 +0x30
```

**Comment by saswatamcode** [comment]
Will TAL!
