### ISSUE TITLE
Crash in `aggregate.(*aggregate).Next`

### ISSUE THREAD

**Issue by GiedriusS** [thanos-community/promql-engine#178]
Got this on a bit older version:

```
-- Logs begin at Wed 2023-02-08 09:59:12 UTC, end at Tue 2023-02-14 10:10:35 UTC. --
Feb 08 12:45:48 XXX thanos[3380578]: panic: runtime error: index out of range [10] with length 10
Feb 08 12:45:48 XXX thanos[3380578]: goroutine 1396810927 [running]:
Feb 08 12:45:48 XXX thanos[3380578]: github.com/thanos-community/promql-engine/execution/aggregate.(*aggregate).Next(0xc05588d930, {0x2b840c0, 0xc0727d3dc0})
Feb 08 12:45:48 XXX thanos[3380578]:      /home/giedrius/go/pkg/mod/github.com/vinted/promql-engine@v0.0.0-20221216110226-ff91f808dd40/execution/aggregate/hashaggregate.go:141 +0xbf0
Feb 08 12:45:48 XXX thanos[3380578]: github.com/thanos-community/promql-engine/execution/exchange.(*concurrencyOperator).pull(0xc04a3e8e40, {0x2b840c0, 0xc0727d3dc0})
Feb 08 12:45:48 XXX thanos[3380578]:      /home/giedrius/go/pkg/mod/github.com/vinted/promql-engine@v0.0.0-20221216110226-ff91f808dd40/execution/exchange/concurrent.go:80 +0xe8
Feb 08 12:45:48 XXX thanos[3380578]: created by github.com/thanos-community/promql-engine/execution/exchange.(*concurrencyOperator).Next.func1
Feb 08 12:45:48 XXX thanos[3380578]:      /home/giedrius/go/pkg/mod/github.com/vinted/promql-engine@v0.0.0-20221216110226-ff91f808dd40/execution/exchange/concurrent.go:56 +0x9b
```

Not sure how to reproduce this or if this is still relevant. I'll try to take look but just adding this in case anyone knows something about this.

Crash is on https://github.com/vinted/promql-engine/blob/ff91f808dd40fc8fa1319fc02098a02ffc5731cb/execution/aggregate/hashaggregate.go#L141.

**Comment by MichaHoffmann** [comment]
What was the query? Feels like `next.Next` had an off-by-one error when sending results to the aggregation.

**Comment by w4rgrum** [comment]
We spotted the same issue on our thanos queriers (Thanos version: v0.30.2) when using `thanos` promql query engine (`--query.promql-engine=thanos` )

```
panic: runtime error: index out of range [10] with length 10
goroutine 7621 [running]:
github.com/thanos-community/promql-engine/execution/aggregate.(*aggregate).Next(0xc000c10dd0, {0x2a93140, 0xc01651f740})
        /go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20230124070417-9e293186b7e4/execution/aggregate/hashaggregate.go:141 +0xbf0
github.com/thanos-community/promql-engine/execution/exchange.(*concurrencyOperator).pull(0xc017bb9f80, {0x2a93140, 0xc01651f740})
        /go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20230124070417-9e293186b7e4/execution/exchange/concurrent.go:80 +0xe8
created by github.com/thanos-community/promql-engine/execution/exchange.(*concurrencyOperator).Next.func1
        /go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20230124070417-9e293186b7e4/execution/exchange/concurrent.go:56 +0x9b
```

We are able to reproduce it by using `topk by` in combination with another aggregation, the smallest query I could get to trigger the issue is:

```
max(topk by(namespace) (1, container_memory_rss))
```

NB: using `prometheus` engine does not trigger the issue for this example.
