### ISSUE TITLE
topk panics when param < 1

### ISSUE THREAD

**Issue by yeya24** [thanos-community/promql-engine#211]
```
		{
			name: "bbb",
			load: `load 30s
http_requests_total{pod="nginx-1", series="1"} 1+1.1x40
http_requests_total{pod="nginx-2", series="2"} 2+2.3x50
http_requests_total{pod="nginx-3", series="3"} 6+0.8x60
http_requests_total{pod="nginx-4", series="3"} 5+2.4x50
http_requests_total{pod="nginx-5", series="1"} 8.4+2.3x50
http_requests_total{pod="nginx-6", series="2"} 2.3+2.3x50
`,
			query: `topk without () (0.5, vector(time()))`,
		}
```

Using float value for the `k` param is actually valid in the old Prometheus engine. Same query won't hit panic in the old engine but panics in the new engine.

Old engine: https://prometheus.demo.do.prometheus.io/graph?g0.expr=topk%20without%20()%20(0.5%2C%20vector(time()))&g0.tab=1&g0.stacked=0&g0.range_input=1h

```
=== RUN   TestInstantQuery/disableOptimizers=true/bbb/disableFallback=false
panic: runtime error: index out of range [0] with length 0

goroutine 108 [running]:
github.com/thanos-community/promql-engine/execution/aggregate.(*kAggregate).aggregate(0x14000546a90, 0xc350, 0x14000077de8, 0x0, {0x1400032ce30, 0x1, 0x1?}, {0x140007d00e0, 0x1, 0x0?})
	/Users/benye/hub/gowork/promql-engine/execution/aggregate/khashaggregate.go:167 +0x414
github.com/thanos-community/promql-engine/execution/aggregate.(*kAggregate).Next(0x14000546a90, {0x1012b3ec8, 0x14000115f80})
	/Users/benye/hub/gowork/promql-engine/execution/aggregate/khashaggregate.go:114 +0x594
github.com/thanos-community/promql-engine/execution/exchange.(*concurrencyOperator).pull(0x14000801a10, {0x1012b3ec8, 0x14000115f80})
	/Users/benye/hub/gowork/promql-engine/execution/exchange/concurrent.go:80 +0xc0
created by github.com/thanos-community/promql-engine/execution/exchange.(*concurrencyOperator).Next.func1
	/Users/benye/hub/gowork/promql-engine/execution/exchange/concurrent.go:56 +0xa0
```

**Comment by yeya24** [comment]
A very similar issue related to this param https://github.com/prometheus/prometheus/blob/main/promql/engine.go#L2334.
The old engine will check the whether the param is within the int64 range.

```
bottomk by (series, pod) ((time() ^ time()), {series="2"} offset -1m52s)
    compatibility_test.go:109: 
        	Error Trace:	/Users/benye/hub/gowork/promqlsmith/example/thanos-engine/compatibility_test.go:109
        	Error:      	Not equal: 
        	            	expected: *errors.errorString(&errors.errorString{s:"Scalar value +Inf overflows int64"})
        	            	actual  : <nil>(<nil>)
        	Test:       	TestPromQLCompatibility
--- FAIL: TestPromQLCompatibility (5.12s)
```

We don't have that check in the new engine so error mismatched.

**Comment by MichaHoffmann** [comment]
Prometheus truncates to int64 and errors if its not possible: https://github.com/prometheus/prometheus/blob/44fcf876caad9a5d28b92a728d2c98c34015d377/promql/engine.go#L2235
