### ISSUE TITLE
SIGSEGV in thanos-query

### ISSUE THREAD

**Issue by vCra** [thanos-community/promql-engine#259]
Seeing the following crash in thanos query v0.30.2
```
2023-05-12T09:58:05+01:00 panic: runtime error: invalid memory address or nil pointer dereference
2023-05-12T09:58:05+01:00 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d6ba04]
2023-05-12T09:58:05+01:00 
2023-05-12T09:58:05+01:00 goroutine 173213 [running]:
2023-05-12T09:58:05+01:00 github.com/thanos-community/promql-engine/worker.(*Worker).start(0xc0023a1d40, 0x2c08060?, {0x2bf4140?, 0xc001177240?})
2023-05-12T09:58:05+01:00 	/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/worker/worker.go:71 +0x84
2023-05-12T09:58:05+01:00 created by github.com/thanos-community/promql-engine/worker.Group.Start
2023-05-12T09:58:05+01:00 	/go/pkg/mod/github.com/thanos-community/promql-engine@v0.0.0-20221115192426-d68c8139c070/worker/worker.go:29 +0x4b
```

**Comment by MichaHoffmann** [comment]
Worker used to have an issue where it was not initialized properly in some aggregations, is that also present on the latest query engine?

**Comment by vCra** [comment]
You're right - looks like this doesn't happen with v0.31 🎉
