### ISSUE TITLE
Crash noticed after merge selects commit

### ISSUE THREAD

**Issue by GiedriusS** [thanos-community/promql-engine#84]
Rolled out the new engine and immediately got this:

```
thanos[947754]: 2022/10/18 12:59:14 http: panic serving 1.2.3.4:48772: runtime error: slice bounds out of range [4:3]                          
thanos[947754]: goroutine 14257 [running]:                                                                                                         
thanos[947754]: net/http.(*conn).serve.func1()                                                                                                     
thanos[947754]: /usr/lib/go-1.19/src/net/http/server.go:1850 +0xbf                                                                                 
thanos[947754]: panic({0x24abd00, 0xc0236b9818})                                                                                                   
thanos[947754]: /usr/lib/go-1.19/src/runtime/panic.go:890 +0x262                                                                                   
thanos[947754]: github.com/thanos-community/promql-engine/logicalplan.dropMatcher(...)                                                             
thanos[947754]: /home/giedrius/go/pkg/mod/github.com/!giedrius!s/promql-engine@v0.0.0-20221018070347-003b77f058a3/logicalplan/merge_selects.go:85  
thanos[947754]: github.com/thanos-community/promql-engine/logicalplan.replaceMatchers.func1(0xc0263784c0)                                          
thanos[947754]: /home/giedrius/go/pkg/mod/github.com/!giedrius!s/promql-engine@v0.0.0-20221018070347-003b77f058a3/logicalplan/merge_selects.go:68 +0x818                                                                                                                                                                                        
thanos[947754]: github.com/thanos-community/promql-engine/logicalplan.traverse(0x1?, 0xc001a68720)                                                 
thanos[947754]: /home/giedrius/go/pkg/mod/github.com/!giedrius!s/promql-engine@v0.0.0-20221018070347-003b77f058a3/logicalplan/plan.go:59 +0x136    
thanos[947754]: github.com/thanos-community/promql-engine/logicalplan.traverse(0xc02635f000?, 0xc001a68720)                                        
thanos[947754]: /home/giedrius/go/pkg/mod/github.com/!giedrius!s/promql-engine@v0.0.0-20221018070347-003b77f058a3/logicalplan/plan.go:64 +0x265
...
```

Don't know how to reproduce ATM but maybe it will be possible to salvage something from the stack trace. Will try to take a look myself soon, just created this in advance. Got this on https://github.com/thanos-community/promql-engine/commit/67a4593d95a391e692c50b630d8ed2ad99076b47.

This points to https://github.com/thanos-community/promql-engine/blob/main/logicalplan/merge_selects.go#L85. Maybe my user traffic hits some kind of edge case.

**Comment by fpetkovski** [comment]
Thanks for reporting this! Did you manage to salvage the PromQL query that was executed? I think I might have added the logical plan optimization to the wrong place, ideally is should be done when executing a query, not when creating one.

**Comment by GiedriusS** [comment]
Can't reproduce anymore after https://github.com/thanos-community/promql-engine/commit/706d7faf6cee4c94f003f213e63205e954bd5dc9 https://github.com/thanos-community/promql-engine/commit/fdc5cac742fcd6c5b725b49aeb4a8b138b166550. Thanks for the fixes :beers:
